spring:
  application:
    name: produto-market
  datasource:
    username: oyivtbtt
    url: jdbc:postgresql://kesavan.db.elephantsql.com/oyivtbtt
    password: SbxMO_txBiujoL_EyC7LOL9Zxv8c7EKP
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true '
    show-sql: 'false'
    hibernate:
      ddl-auto: none
  database:
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgresql